name: Demoworkflow
on: workflow_dispatch
jobs:
  demojob:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: !
          echo "Hi"
          echo "Hello"
      - name: Say welcome to the world of github action
        run: echo "welcome to the world of github action"
